#
#  Copyright 2023 Davide Bettio <bettio@uninstall.it>
#
#  SPDX-License-Identifier: Apache-2.0
#

name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp: ['26.0']
        rebar3: ['3.22.1']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Compile
        run: rebar3 compile
